package frc.robot.subsystems;

import static edu.wpi.first.units.Units.*;

import java.util.function.Supplier;

import com.ctre.phoenix6.SignalLogger;
import com.ctre.phoenix6.Utils;
import com.ctre.phoenix6.swerve.SwerveDrivetrainConstants;
import com.ctre.phoenix6.swerve.SwerveModuleConstants;
import com.ctre.phoenix6.swerve.SwerveRequest;

import edu.wpi.first.math.Matrix;
import edu.wpi.first.math.VecBuilder;
import edu.wpi.first.math.geometry.Pose2d;
import edu.wpi.first.math.geometry.Rotation2d;
import edu.wpi.first.math.geometry.Translation2d;
import edu.wpi.first.math.kinematics.ChassisSpeeds;
import edu.wpi.first.math.numbers.N1;
import edu.wpi.first.math.numbers.N3;
import edu.wpi.first.wpilibj.DriverStation;
import edu.wpi.first.wpilibj.DriverStation.Alliance;
import edu.wpi.first.wpilibj.Notifier;
import edu.wpi.first.wpilibj.RobotController;
import edu.wpi.first.wpilibj.smartdashboard.Field2d;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj2.command.Command;
import edu.wpi.first.wpilibj2.command.Subsystem;
import edu.wpi.first.wpilibj2.command.sysid.SysIdRoutine;

import edu.wpi.first.apriltag.AprilTagFieldLayout;
import edu.wpi.first.apriltag.AprilTagFields;
import frc.robot.generated.TunerConstants;
import frc.robot.generated.TunerConstants.TunerSwerveDrivetrain;
import frc.robot.Constants.ShootingConstants;
import frc.util.Vision;

import com.pathplanner.lib.auto.AutoBuilder;
import com.pathplanner.lib.config.PIDConstants;
import com.pathplanner.lib.config.RobotConfig;
import com.pathplanner.lib.controllers.PPHolonomicDriveController;
import com.ctre.phoenix6.swerve.SwerveModule.DriveRequestType;
/**
 * Class that extends the Phoenix 6 SwerveDrivetrain class and implements
 * Subsystem so it can easily be used in command-based projects.
 *
 * Generated by the 2026 Tuner X Swerve Project Generator
 * https://v6.docs.ctr-electronics.com/en/stable/docs/tuner/tuner-swerve/index.html
 */
public class CommandSwerveDrivetrain extends TunerSwerveDrivetrain implements Subsystem {
    private static final double kSimLoopPeriod = 0.004; // 4 ms
    private Notifier m_simNotifier = null;
    private double m_lastSimTime;

    /* Blue alliance sees forward as 0 degrees (toward red alliance wall) */
    private static final Rotation2d kBlueAlliancePerspectiveRotation = Rotation2d.kZero;
    /* Red alliance sees forward as 180 degrees (toward blue alliance wall) */
    private static final Rotation2d kRedAlliancePerspectiveRotation = Rotation2d.k180deg;
    /* Keep track if we've ever applied the operator perspective before or not */
    private boolean m_hasAppliedOperatorPerspective = false;

    /* Limelight vision — two cameras with fallback */
    private Vision kLimelight1 = new Vision("limelight-llone");
    private Vision kLimelight2 = new Vision("limelight-lltwo");

    /* AprilTag field layout */
    private AprilTagFieldLayout kFieldLayout = AprilTagFieldLayout.loadField(AprilTagFields.k2026RebuiltWelded);

    /* Swerve requests to apply during SysId characterization */
    private final SwerveRequest.SysIdSwerveTranslation m_translationCharacterization = new SwerveRequest.SysIdSwerveTranslation();
    private final SwerveRequest.SysIdSwerveSteerGains m_steerCharacterization = new SwerveRequest.SysIdSwerveSteerGains();
    private final SwerveRequest.SysIdSwerveRotation m_rotationCharacterization = new SwerveRequest.SysIdSwerveRotation();

    /* SysId routine for characterizing translation. This is used to find PID gains for the drive motors. */
    private final SysIdRoutine m_sysIdRoutineTranslation = new SysIdRoutine(
        new SysIdRoutine.Config(
            null,        // Use default ramp rate (1 V/s)
            Volts.of(4), // Reduce dynamic step voltage to 4 V to prevent brownout
            null,        // Use default timeout (10 s)
            state -> SignalLogger.writeString("state", state.toString())
        ),
        new SysIdRoutine.Mechanism(
            output -> setControl(m_translationCharacterization.withVolts(output)),
            null,
            this
        )
    );

    /* SysId routine for characterizing steer. This is used to find PID gains for the steer motors. */
    private final SysIdRoutine m_sysIdRoutineSteer = new SysIdRoutine(
        new SysIdRoutine.Config(
            null,        // Use default ramp rate (1 V/s)
            Volts.of(7), // Use dynamic voltage of 7 V
            null,        // Use default timeout (10 s)
            state -> SignalLogger.writeString("state", state.toString())
        ),
        new SysIdRoutine.Mechanism(
            volts -> setControl(m_steerCharacterization.withVolts(volts)),
            null,
            this
        )
    );

    /*
     * SysId routine for characterizing rotation.
     * This is used to find PID gains for the FieldCentricFacingAngle HeadingController.
     * See the documentation of SwerveRequest.SysIdSwerveRotation for info on importing the log to SysId.
     */
    private final SysIdRoutine m_sysIdRoutineRotation = new SysIdRoutine(
        new SysIdRoutine.Config(
            /* This is in radians per second², but SysId only supports "volts per second" */
            Volts.of(Math.PI / 6).per(Second),
            /* This is in radians per second, but SysId only supports "volts" */
            Volts.of(Math.PI),
            null, // Use default timeout (10 s)
            state -> SignalLogger.writeString("state", state.toString())
        ),
        new SysIdRoutine.Mechanism(
            output -> {
                /* output is actually radians per second, but SysId only supports "volts" */
                setControl(m_rotationCharacterization.withRotationalRate(output.in(Volts)));
            },
            null,
            this
        )
    );

    /* The SysId routine to test */
    private SysIdRoutine m_sysIdRoutineToApply = m_sysIdRoutineTranslation;

    /* PathPlanner auto objects */
    private Field2d field = new Field2d();
    private SwerveRequest.ApplyRobotSpeeds autoRequest = new SwerveRequest.ApplyRobotSpeeds()
        .withDriveRequestType(DriveRequestType.Velocity);

    /**
     * Constructs a CTRE SwerveDrivetrain using the specified constants.
     * <p>
     * This constructs the underlying hardware devices, so users should not construct
     * the devices themselves. If they need the devices, they can access them through
     * getters in the classes.
     *
     * @param drivetrainConstants   Drivetrain-wide constants for the swerve drive
     * @param modules               Constants for each specific module
     */
    public CommandSwerveDrivetrain(
        SwerveDrivetrainConstants drivetrainConstants,
        SwerveModuleConstants<?, ?, ?>... modules
    ) {
        super(drivetrainConstants, modules);
        if (Utils.isSimulation()) {
            startSimThread();
        }
        configureAutoBuilder();
    }

    /**
     * Constructs a CTRE SwerveDrivetrain using the specified constants.
     * <p>
     * This constructs the underlying hardware devices, so users should not construct
     * the devices themselves. If they need the devices, they can access them through
     * getters in the classes.
     *
     * @param drivetrainConstants     Drivetrain-wide constants for the swerve drive
     * @param odometryUpdateFrequency The frequency to run the odometry loop. If
     *                                unspecified or set to 0 Hz, this is 250 Hz on
     *                                CAN FD, and 100 Hz on CAN 2.0.
     * @param modules                 Constants for each specific module
     */
    public CommandSwerveDrivetrain(
        SwerveDrivetrainConstants drivetrainConstants,
        double odometryUpdateFrequency,
        SwerveModuleConstants<?, ?, ?>... modules
    ) {
        super(drivetrainConstants, odometryUpdateFrequency, modules);
        if (Utils.isSimulation()) {
            startSimThread();
        }
        configureAutoBuilder();
    }

    /**
     * Constructs a CTRE SwerveDrivetrain using the specified constants.
     * <p>
     * This constructs the underlying hardware devices, so users should not construct
     * the devices themselves. If they need the devices, they can access them through
     * getters in the classes.
     *
     * @param drivetrainConstants       Drivetrain-wide constants for the swerve drive
     * @param odometryUpdateFrequency   The frequency to run the odometry loop. If
     *                                  unspecified or set to 0 Hz, this is 250 Hz on
     *                                  CAN FD, and 100 Hz on CAN 2.0.
     * @param odometryStandardDeviation The standard deviation for odometry calculation
     *                                  in the form [x, y, theta]ᵀ, with units in meters
     *                                  and radians
     * @param visionStandardDeviation   The standard deviation for vision calculation
     *                                  in the form [x, y, theta]ᵀ, with units in meters
     *                                  and radians
     * @param modules                   Constants for each specific module
     */
    public CommandSwerveDrivetrain(
        SwerveDrivetrainConstants drivetrainConstants,
        double odometryUpdateFrequency,
        Matrix<N3, N1> odometryStandardDeviation,
        Matrix<N3, N1> visionStandardDeviation,
        SwerveModuleConstants<?, ?, ?>... modules
    ) {
        super(drivetrainConstants, odometryUpdateFrequency, odometryStandardDeviation, visionStandardDeviation, modules);
        if (Utils.isSimulation()) {
            startSimThread();
        }
        configureAutoBuilder();
    }

    /**
     * Returns a command that applies the specified control request to this swerve drivetrain.
     *
     * @param request Function returning the request to apply
     * @return Command to run
     */
    public Command applyRequest(Supplier<SwerveRequest> request) {
        return run(() -> this.setControl(request.get()));
    }

    /**
     * Configures PathPlanner's AutoBuilder for autonomous path following.
     */
    private void configureAutoBuilder() {
        try {
            var config = RobotConfig.fromGUISettings();
            AutoBuilder.configure(
                () -> getState().Pose, // Taken from CTRE Examples: https://github.com/CrossTheRoadElec/Phoenix6-Examples/blob/main/java/SwerveWithPathPlanner/src/main/java/frc/robot/subsystems/CommandSwerveDrivetrain.java#L197
                this::resetPose,
                () -> getState().Speeds,
                (speeds) -> this.setControl(autoRequest.withSpeeds(speeds)),
                new PPHolonomicDriveController(
                    new PIDConstants(5.0, 0.0, 0.0),
                    new PIDConstants(5.0, 0.0, 0.0)
                ),
                config,
                // Assume the path needs to be flipped for Red vs Blue, this is normally the case
                () -> DriverStation.getAlliance().orElse(Alliance.Blue) == Alliance.Red,
                this
            );
        } catch (Exception ex) {
            DriverStation.reportError("Failed to load PathPlanner config and configure AutoBuilder", ex.getStackTrace());
        }
    }

    /**
     * Runs the SysId Quasistatic test in the given direction for the routine
     * specified by {@link #m_sysIdRoutineToApply}.
     *
     * @param direction Direction of the SysId Quasistatic test
     * @return Command to run
     */
    public Command sysIdQuasistatic(SysIdRoutine.Direction direction) {
        return m_sysIdRoutineToApply.quasistatic(direction);
    }

    /**
     * Runs the SysId Dynamic test in the given direction for the routine
     * specified by {@link #m_sysIdRoutineToApply}.
     *
     * @param direction Direction of the SysId Dynamic test
     * @return Command to run
     */
    public Command sysIdDynamic(SysIdRoutine.Direction direction) {
        return m_sysIdRoutineToApply.dynamic(direction);
    }

    @Override
    public void periodic() {
        /*
         * Periodically try to apply the operator perspective.
         * If we haven't applied the operator perspective before, then we should apply it regardless of DS state.
         * This allows us to correct the perspective in case the robot code restarts mid-match.
         * Otherwise, only check and apply the operator perspective if the DS is disabled.
         * This ensures driving behavior doesn't change until an explicit disable event occurs during testing.
         */
        if (!m_hasAppliedOperatorPerspective || DriverStation.isDisabled()) {
            DriverStation.getAlliance().ifPresent(allianceColor -> {
                setOperatorPerspectiveForward(
                    allianceColor == Alliance.Red
                        ? kRedAlliancePerspectiveRotation
                        : kBlueAlliancePerspectiveRotation
                );
                m_hasAppliedOperatorPerspective = true;
            });
        }

        /* Limelight vision integration — two cameras with fallback */
        SmartDashboard.putBoolean("Limelight 1 TV", kLimelight1.getTV());
        SmartDashboard.putBoolean("Limelight 2 TV", kLimelight2.getTV());
        SmartDashboard.putBoolean("Sees AprilTag LL1", kLimelight1.getTV());
              SmartDashboard.putBoolean("Sees AprilTag LL2", kLimelight2.getTV());

        /* AprilTag floor distance from each Limelight (2D, ignoring height) */
        if (kLimelight1.getTV()) {
            var tagPose1 = kLimelight1.getRobotTagRelativePose().getTranslation();
            double dist1 = Math.sqrt(tagPose1.getX() * tagPose1.getX()
                                   + tagPose1.getZ() * tagPose1.getZ());
            SmartDashboard.putNumber("LL1 AprilTag Distance (m)", dist1);
            SmartDashboard.putNumber("LL1 AprilTag ID", kLimelight1.getTagID());
        }
        if (kLimelight2.getTV()) {
            var tagPose2 = kLimelight2.getRobotTagRelativePose().getTranslation();
            double dist2 = Math.sqrt(tagPose2.getX() * tagPose2.getX()
                                   + tagPose2.getZ() * tagPose2.getZ());
            SmartDashboard.putNumber("LL2 AprilTag Distance (m)", dist2);
            SmartDashboard.putNumber("LL2 AprilTag ID", kLimelight2.getTagID());
        }

        //SmartDashboard.putNumber("CANcoder angle 1",  )
        if (kLimelight1.getTV()) {
            addVisionMeasurement(
                kLimelight1.getEstimatedRoboPose(),
                Utils.fpgaToCurrentTime(kLimelight1.getTimestamp()),
                kLimelight1.getStandardDeviations()
            );
        }
        if (kLimelight2.getTV()) {
            addVisionMeasurement(
                kLimelight2.getEstimatedRoboPose(),
                Utils.fpgaToCurrentTime(kLimelight2.getTimestamp()),
                kLimelight2.getStandardDeviations()
            );
        }
        

        /* Limelight camera streams (port-forwarded through roboRIO USB) */
        SmartDashboard.putString("Limelight 1 Stream",
            "http://10.7.81.2:5800/stream.mjpg");
        SmartDashboard.putString("Limelight 2 Stream",
            "http://10.7.81.2:5810/stream.mjpg");

        /* 3D Robot Pose from odometry */
        SmartDashboard.putNumber("Robot Pose X (m)", getState().Pose.getX());
        SmartDashboard.putNumber("Robot Pose Y (m)", getState().Pose.getY());
        SmartDashboard.putNumber("Robot Pose Heading (deg)", getState().Pose.getRotation().getDegrees());

        /* Robot velocity */
        SmartDashboard.putNumber("Robot Velocity X (m/s)", getState().Speeds.vxMetersPerSecond);
        SmartDashboard.putNumber("Robot Velocity Y (m/s)", getState().Speeds.vyMetersPerSecond);

        SmartDashboard.putData("field2d", this.field);
        this.field.setRobotPose(getState().Pose);
    }

    private void startSimThread() {
        m_lastSimTime = Utils.getCurrentTimeSeconds();

        /* Run simulation at a faster rate so PID gains behave more reasonably */
        m_simNotifier = new Notifier(() -> {
            final double currentTime = Utils.getCurrentTimeSeconds();
            double deltaTime = currentTime - m_lastSimTime;
            m_lastSimTime = currentTime;

            /* use the measured time delta, get battery voltage from WPILib */
            updateSimState(deltaTime, RobotController.getBatteryVoltage());
        });
        m_simNotifier.startPeriodic(kSimLoopPeriod);
    }

    /**
     * Gets the current robot pose.
     * @return Current robot pose
     */
    public Pose2d getPose() {
        return getState().Pose;
    }

    /**
     * Gets the pose of a specific AprilTag on the field.
     * @param AprilTagID The ID of the AprilTag
     * @return Pose2d of the AprilTag
     */
    public Pose2d getTagPose(int AprilTagID) {
        return kFieldLayout.getTagPose(AprilTagID).get().toPose2d();
    }

    /**
     * Gets the relative translation from the robot to a specific AprilTag.
     * @param apriltagID The ID of the AprilTag
     * @return Translation2d relative to the AprilTag
     */
    public Translation2d getTranslationRelative(int apriltagID) {
        return getPose().getTranslation()
            .minus(
                kFieldLayout.getTagPose(apriltagID).get().getTranslation().toTranslation2d()
            );
    }

    /**
     * Gets the relative rotation from the robot to a specific AprilTag.
     * @param apriltagID The ID of the AprilTag
     * @return Rotation2d relative to the AprilTag
     */
    public Rotation2d getRotationRelative(int apriltagID) {
        return getPose().getTranslation()
            .minus(
                getTagPose(apriltagID).getTranslation()
            )
            .unaryMinus()
            .getAngle();
    }

    /**
     * Computes the hub center point by taking the midpoint between two AprilTags
     * and offsetting it behind the tag wall by HUB_DEPTH_OFFSET meters.
     * Uses the average tag facing direction to determine "behind."
     * @param tagID1 First AprilTag ID
     * @param tagID2 Second AprilTag ID
     * @return Translation2d of the hub center on the field
     */
    private Translation2d getHubCenter(int tagID1, int tagID2) {
        Pose2d tag1 = getTagPose(tagID1);
        Pose2d tag2 = getTagPose(tagID2);

        // Midpoint of the two tags (center of the wall)
        Translation2d midpoint = tag1.getTranslation()
            .plus(tag2.getTranslation())
            .div(2.0);

        // Average the tag facing directions — tags face outward from the hub,
        // so we offset OPPOSITE to their facing direction (into the hub center)
        Rotation2d avgFacing = tag1.getRotation()
            .plus(tag2.getRotation())
            .div(2.0);

        // Offset the midpoint INTO the hub (opposite of tag facing direction)
        Translation2d offset = new Translation2d(-ShootingConstants.HUB_DEPTH_OFFSET, avgFacing);
        return midpoint.plus(offset);
    }

    /**
     * Gets the relative rotation from the robot to the midpoint between two AprilTags.
     * @param tagID1 The ID of the first AprilTag
     * @param tagID2 The ID of the second AprilTag
     * @return Rotation2d pointing toward the midpoint of the two tags
     */
    public Rotation2d getRotationRelativeMidpoint(int tagID1, int tagID2) {
        Translation2d hubCenter = getHubCenter(tagID1, tagID2);
        return hubCenter
            .minus(getPose().getTranslation())
            .getAngle()
            .rotateBy(Rotation2d.k180deg);
    }

    /**
     * Gets the distance in meters from the robot to the midpoint between two AprilTags.
     * @param tagID1 The ID of the first AprilTag
     * @param tagID2 The ID of the second AprilTag
     * @return Distance in meters
     */
    public double getDistanceToMidpoint(int tagID1, int tagID2) {
        Translation2d hubCenter = getHubCenter(tagID1, tagID2);
        return getPose().getTranslation().getDistance(hubCenter);
    }

    /**
     * Gets the current field-relative chassis speeds.
     * @return ChassisSpeeds with vx, vy in m/s and omega in rad/s
     */
    public ChassisSpeeds getFieldRelativeVelocity() {
        return getState().Speeds;
    }

    /**
     * Computes an aim-compensated rotation toward the midpoint of two AprilTags,
     * accounting for robot velocity so the ball lands on target while driving.
     * 
     * The compensation works by computing where the robot will be when the ball 
     * arrives at the target (based on time-of-flight), then aiming at the target
     * from that predicted position instead of the current position.
     * 
     * Uses the actual distance-based exit velocity rather than a fixed constant,
     * since shooter wheel speed varies with distance.
     * 
     * @param tagID1 First AprilTag ID
     * @param tagID2 Second AprilTag ID
     * @return Rotation2d with velocity compensation applied
     */
    public Rotation2d getAimCompensatedRotation(int tagID1, int tagID2) {
        // Target = hub center (midpoint offset behind the tag wall)
        Translation2d target = getHubCenter(tagID1, tagID2);

        Translation2d robotPos = getPose().getTranslation();
        double distance = robotPos.getDistance(target);

        // Get the actual exit velocity based on current distance
        double ballExitSpeedMps = Shooter.getExitVelocityMps(distance);

        // Time of flight = distance / ball speed
        double tof = (ballExitSpeedMps > 0) ? distance / ballExitSpeedMps : 0;

        // Predict where the ball will be offset by robot velocity * time-of-flight
        // We subtract the offset from the target so we aim "ahead"
        ChassisSpeeds speeds = getFieldRelativeVelocity();
        Translation2d velocityOffset = new Translation2d(
            speeds.vxMetersPerSecond * tof,
            speeds.vyMetersPerSecond * tof
        );

        // Aim at: target minus the velocity offset (i.e. lead the shot)
        Translation2d compensatedTarget = target.minus(velocityOffset);

        return compensatedTarget
            .minus(robotPos)
            .getAngle()
            .rotateBy(Rotation2d.k180deg);
    }

    /**
     * Gets the rotation from the robot to an arbitrary field-relative point.
     * The robot will face AWAY from the point (shooter faces the point, robot drives backward).
     * @param target The field-relative point to aim at
     * @return Rotation2d pointing the shooter toward the target
     */
    public Rotation2d getRotationToFieldPoint(Translation2d target) {
        return target
            .minus(getPose().getTranslation())
            .getAngle()
            .rotateBy(Rotation2d.k180deg);
    }

    /**
     * Gets the floor-plane distance (meters) to the nearest visible AprilTag
     * using Limelight target-space pose data. Checks LL1 first, then LL2.
     * Returns 0 if no tag is visible on either camera.
     */
    public double getLimelightAprilTagDistance() {
        if (kLimelight1.getTV()) {
            var t = kLimelight1.getRobotTagRelativePose().getTranslation();
            return Math.sqrt(t.getX() * t.getX() + t.getZ() * t.getZ());
        }
        if (kLimelight2.getTV()) {
            var t = kLimelight2.getRobotTagRelativePose().getTranslation();
            return Math.sqrt(t.getX() * t.getX() + t.getZ() * t.getZ());
        }
        return 0.0;
    }
}
